import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";

// Topic-matched links from each article to the setup guides it discusses.
//
// Search Console (2026-09-16) showed six guides as "Discovered/Crawled —
// currently not indexed" with "Referring page: None detected": the only
// internal link to any guide was the /documentation hub. The articles are the
// most-crawled pages on the site, so linking guides from them is how Google
// finds and values them. Keep this map here rather than in the article copy —
// BlogPost.tsx is regenerated by Lovable exports; this file is not.

type Guide = { path: string; title: string };

const GUIDES = {
  wholesalePricing: { path: "/wholesale-pricing-guide", title: "Enable wholesale pricing on Shopify" },
  pricingRules: { path: "/create-pricing-rule-guide", title: "Create wholesale pricing rules" },
  customerGroups: { path: "/customer-group-guide", title: "Create wholesale customer groups" },
  approveCustomers: { path: "/accept-reject-customers-guide", title: "Approve or reject wholesale customers" },
  bulkUpload: { path: "/bulk-upload-guide", title: "Set up CSV/Excel bulk ordering" },
  volumeDiscounts: { path: "/volume-discount-guide", title: "Set up volume and tiered pricing" },
  registrationForm: { path: "/registration-form-guide", title: "Create a wholesale registration form" },
  enableRegistration: { path: "/enable-registration-form-guide", title: "Enable registration forms on your store" },
  registrationEmail: { path: "/registration-email-guide", title: "Configure registration form emails" },
  registrationTranslations: { path: "/registration-translations-guide", title: "Translate your registration form" },
  registrationCaptcha: { path: "/registration-captcha-guide", title: "Add CAPTCHA to registration forms" },
  orderLimits: { path: "/order-limits-guide", title: "Configure wholesale order limits" },
  enableOrderLimits: { path: "/enable-order-limits-guide", title: "Enable order limits on your store" },
  paymentTerms: { path: "/custom-payment-terms-guide", title: "Create custom payment terms (Net 30/60)" },
  shippingRules: { path: "/custom-shipping-rules-guide", title: "Set up custom shipping rules" },
  lockHidePrice: { path: "/lock-page-hide-price-guide", title: "Lock pages and hide prices" },
  quickOrder: { path: "/quick-order-form-guide", title: "Set up a quick order form" },
} satisfies Record<string, Guide>;

const G = GUIDES;

export const RELATED_GUIDES: Record<string, Guide[]> = {
  "sami-b2b-wholesale-pricing-alternatives": [G.pricingRules, G.registrationForm, G.orderLimits, G.quickOrder],
  "bss-b2b-wholesale-pricing-alternatives": [G.pricingRules, G.registrationForm, G.paymentTerms, G.quickOrder],
  "shopify-revenue-leaks": [G.registrationForm, G.registrationEmail, G.registrationCaptcha, G.quickOrder],
  "sparklayer-alternatives": [G.pricingRules, G.paymentTerms, G.orderLimits, G.quickOrder],
  "wholesale-gorilla-alternatives": [G.pricingRules, G.volumeDiscounts, G.approveCustomers, G.lockHidePrice],
  "shopify-wholesale-registration-form": [
    G.registrationForm, G.enableRegistration, G.approveCustomers,
    G.registrationEmail, G.registrationTranslations, G.registrationCaptcha,
  ],
  "best-shopify-wholesale-apps": [G.pricingRules, G.volumeDiscounts, G.paymentTerms, G.quickOrder, G.lockHidePrice],
  "introducing-page-lock-hide-price": [G.lockHidePrice, G.customerGroups, G.approveCustomers],
  "shopify-b2b-build-complete-wholesale-store": [
    G.wholesalePricing, G.customerGroups, G.registrationForm, G.bulkUpload, G.shippingRules,
  ],
  "guide-creating-wholesale-store-shopify": [
    G.wholesalePricing, G.pricingRules, G.bulkUpload, G.lockHidePrice, G.shippingRules,
  ],
  "best-shopify-wholesale-apps-2026": [G.pricingRules, G.volumeDiscounts, G.orderLimits, G.bulkUpload],
  "bmt-perfect-for-d2c-brands-expanding-wholesale": [G.wholesalePricing, G.customerGroups, G.registrationForm],
  "bmt-smarter-choice-than-traditional-wholesale-apps": [G.wholesalePricing, G.pricingRules, G.enableOrderLimits],
  "bmt-b2b-partner-established-us-shopify-store": [G.customerGroups, G.paymentTerms, G.shippingRules],
  "merchant-increased-b2b-revenue-40-percent": [G.volumeDiscounts, G.bulkUpload, G.quickOrder],
  "shopify-wholesale-app-small-business": [G.wholesalePricing, G.pricingRules, G.orderLimits, G.enableOrderLimits],
};

// For articles added after this map was written.
const DEFAULT_GUIDES: Guide[] = [G.wholesalePricing, G.pricingRules, G.registrationForm, G.quickOrder];

const RelatedGuides = ({ slug }: { slug: string }) => {
  const guides = RELATED_GUIDES[slug] ?? DEFAULT_GUIDES;
  return (
    <section className="mt-12 pt-8 border-t border-border/50">
      <h2 className="text-2xl sm:text-3xl font-bold text-foreground mb-2 tracking-tight">Set it up in your store</h2>
      <p className="text-muted-foreground mb-6">Step-by-step guides for the features covered above.</p>
      <ul className="grid gap-3 sm:grid-cols-2">
        {guides.map((g) => (
          <li key={g.path}>
            <Link
              to={g.path}
              className="group flex h-full items-center justify-between gap-3 rounded-xl border border-border/50 bg-card/50 px-4 py-3 text-foreground transition-colors hover:border-primary/40 hover:bg-card"
            >
              <span className="font-medium">{g.title}</span>
              <ArrowRight className="h-4 w-4 shrink-0 text-primary transition-transform group-hover:translate-x-0.5" />
            </Link>
          </li>
        ))}
      </ul>
      <Link to="/documentation" className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-primary hover:underline">
        Browse all setup guides <ArrowRight className="h-3.5 w-3.5" />
      </Link>
    </section>
  );
};

export default RelatedGuides;
